name: helpers-read-yaml

on:
  push:
  workflow_dispatch:

jobs:
  read-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: read-yaml-file
        uses: pietrobolcato/action-read-yaml@1.0.0
        id: read_action_js
        with:
          config: ${{ github.workspace }}/config.yaml

      - name: use-yaml-file
        run: |
          echo namespace: ${{ steps.read_action_js.outputs['namespace'] }}
          echo location: ${{ steps.read_action_js.outputs['location'] }}
          echo environment: ${{ steps.read_action_js.outputs['environment'] }}
          echo resource_group_name: ${{ steps.read_action_js.outputs['resource_group_name'] }}
